//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerItem
    {
        public int BannerItemId { get; set; }
        public int BannerId { get; set; }
        public string ImageUrl { get; set; }
        public string SponsorUrl { get; set; }
        public int Position { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string BannerName { get; set; }
    
        public virtual Banner Banner { get; set; }
    }
}
