//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public Banner()
        {
            this.BannerItems = new HashSet<BannerItem>();
            this.PageBanners = new HashSet<PageBanner>();
        }
    
        public int BannerId { get; set; }
        public bool IsDefault { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsSplashImage { get; set; }
    
        public virtual ICollection<BannerItem> BannerItems { get; set; }
        public virtual ICollection<PageBanner> PageBanners { get; set; }
    }
}
