//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoritePage
    {
        public int FavoritePageId { get; set; }
        public int UserKey { get; set; }
        public int PageId { get; set; }
        public int PageItemId { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual PageItem PageItem { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
