//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitCounterDetail
    {
        public string SponsorType { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string SponsorUrl { get; set; }
        public string ClientIdentity { get; set; }
        public Nullable<System.DateTime> HitOn { get; set; }
    }
}
