//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitCounter
    {
        public int HitCounterId { get; set; }
        public int SponsorId { get; set; }
        public int SponsorTypeId { get; set; }
        public string ClientIdentiy { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> HitOn { get; set; }
    }
}
