//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NJFairgroundDBEntities : DbContext
    {
        public NJFairgroundDBEntities()
            : base("name=NJFairgroundDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<PageHeader> PageHeaders { get; set; }
        public DbSet<PageItem> PageItems { get; set; }
        public DbSet<PageItemDetail> PageItemDetails { get; set; }
    }
}
