//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJFairground.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int NotificationLogId { get; set; }
        public string NotifiactionToken { get; set; }
        public int DeviceRegistryId { get; set; }
        public int PageItemId { get; set; }
        public int StatusId { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime NotifiedOn { get; set; }
        public Nullable<System.DateTime> ReadOn { get; set; }
    
        public virtual DeviceRegistry DeviceRegistry { get; set; }
        public virtual PageItem PageItem { get; set; }
    }
}
